### ISSUE TITLE
Implicit declaration of function `__io_putchar` and  `__io_getchar`

### ISSUE THREAD

**Issue by nedseb** [letssteam/codal-stm32#18]
The following lines should be added to [syscalls.c](https://github.com/letssteam/codal-stm32/blob/4e9fb490f56a71f43fb62c702b5bc21e50ab711d/src/syscalls.c#L57) :
```c++
extern int __io_putchar(int ch) __attribute__((weak));
extern int __io_getchar(void) __attribute__((weak));
```

**Comment by jnthbdn** [comment]
Add with PR #19
